# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            wiks.wiki
tagline:          "The personal is personal."
description:      "The public, practical, personal, and political journal of your favorite high IQ bitty."
url:              https://www.wiks.wiki
baseurl:
author:           ""
name:             "WIKS"
excerpt_separator: "<!-- more -->"
paginate:         5

# Custom vars
version:          2.1.0
repo:           https://github.com/w1k5/w1k5.github.io

# Plugins/Gems
plugins:          [jekyll-paginate, jekyll-seo-tag, jekyll-last-modified-at, jekyll-sitemap, jekyll-feed, jekyll-algolia]
last-modified-at:
    date-format: '%d-%b-%y'

# Disqus Comments
disqus:
    # Leave shortname blank to disable comments site-wide.
    # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
    shortname: wiks-wiki

# Algolia
algolia:
  application_id: 3LIPBJALCC
  index_name:     dev_wikswiki # You can replace that with whatever name you want
  search_only_api_key: 589ecf509adf643496923be4a01fe8c7
